### ISSUE TITLE
Strimzi OOM issue

### ISSUE THREAD

**Issue by vidister** [monogon-dev/NetMeta#101]
We set up Netmeta on a new machine and Strimzi didn't come up since it was hitting the memory limit of 256 Mb and was OOM killed. Maybe it spawns a thread per CPU core and runs out of memory on large machines? Here we have 32 Cores.

We should increase the limit in `deploy/single-node/strimzi/deployment.cue`

**Comment by fionera** [comment]
Should be fixed with https://github.com/monogon-dev/NetMeta/commit/1734a30dac06ba9289bcb115e0db95e5d47edc68 Can you test that?

**Comment by fionera** [comment]
Cannot be reproduced. Closing for now
