### ISSUE TITLE
Dashboards: More user friendly source/interface selector

### ISSUE THREAD

**Issue by vidister** [monogon-dev/NetMeta#103]
The interface selector displays all interface IDs of all devices - if two devices have overlapping interface IDs they are merged and the description of one interface is displayed.

When a source is selected, NetMeta should filter the list of available interfaces.

Supporting overlapping interface IDs when displaying all sources is tricky.
For this to work Grafana would have to set both variables, `sampler` and `interface`, from the interface selector. Afaik that is not supported.
I can imagine a few hacks to build this, but none of them excites me. Any ideas?

**Comment by fionera** [comment]
Instead of displaying only the id we can join the SamplerAddr with the ID to a String and use that as a selector. Since the SamplerAddr is a string anyway it shouldn't be such a big perfomance hit

**Comment by fionera** [comment]
Implemented with https://github.com/monogon-dev/NetMeta/commit/a4d132a34f7d42e0fc667c58fa88e0959c317937
