### ISSUE TITLE
Allow to set custom names for AS

### ISSUE THREAD

**Issue by n0emis** [monogon-dev/NetMeta#127]
We have different internal (private) AS in use and would greatly benefit with the ability to add custom entries to the `autnums`-table. A config-option for this would be nice

**Comment by fionera** [comment]
Thanks for the issue <3 I will try to get this added on monday :)

**Comment by fionera** [comment]
Didn't finish it yesterday but its now waiting for review :) https://review.monogon.dev/c/NetMeta/+/1940

It will allow definition of custom ASNs which even override the existing ones
