### ISSUE TITLE
Naming for sources

### ISSUE THREAD

**Issue by leoluk** [monogon-dev/NetMeta#53]
IP -> Name LUT for flow sources

**Comment by fionera** [comment]
Currently the portmirror always exports 127.0.0.1 as its source ip. this should be configurable

**Comment by fionera** [comment]
The portmirror supports overriding the samplerAddress with https://github.com/monogon-dev/NetMeta/commit/662c91a018f42b0e168be6d059f3e82474dae408 and https://review.monogon.dev/c/NetMeta/+/966 implements a lookup for routers. Should we also allow lookups for specific IPs?

**Comment by fionera** [comment]
Implemented with https://github.com/monogon-dev/NetMeta/commit/911cecffbb0311e21a9fdafe722aea3c8e00b291
