### ISSUE TITLE
Efficient v6 subnet queries

### ISSUE THREAD

**Issue by leoluk** [monogon-dev/NetMeta#57]
Trivial with an IPv4, surprisingly non-trivial with IPv6 because it's a `FixedString(16)` and we can't do bitwise ops on it.

https://github.com/ClickHouse/ClickHouse/issues/6808

https://github.com/ClickHouse/ClickHouse/issues/11245

This is the only way to do a bitwise query:

    select count(Date) from flows_raw where EType = 0x0800 and IPv6CIDRToRange(DstAddr, 104).1 = toIPv6('::44.0.0.0');

Calculate the bitmask by adding 96 to the CIDR mask (i.e. `/24 == 24 + 96 == 120`).
    
If you want to filter for the `44.0.0.0/8` network, the query for the "Custom SQL" field would be `IPv6CIDRToRange(DstAddr, 104).1 = toIPv6('::44.0.0.0')`.

For known query patterns, it would be advisable to materialize computed columns.

**Comment by fionera** [comment]
In the current version of clickhouse there is a function for this:
https://clickhouse.com/docs/en/sql-reference/functions/ip-address-functions#isipaddressinrange

**Comment by fionera** [comment]
Implemented with https://github.com/monogon-dev/NetMeta/commit/305280625aa772285a185e6b6d8a427ce3157d08
