### ISSUE TITLE
Flow direction inference for sFlow

### ISSUE THREAD

**Issue by leoluk** [monogon-dev/NetMeta#60]

**Comment by fionera** [comment]
Implemented with https://github.com/monogon-dev/NetMeta/commit/8c5f861d89903d858b7266187e703f3d20ea4c07. Still missing docs but here a quick rundown: 

```
sampler: "::ffff:127.0.0.1": isIncomingFlow: [{
     DstAS: 1337
     DstAddr: "::ffff:1.2.3.4"
    }, {
     SrcAddrInRange: "1.2.3.4/31"
    }]
```
This marks all traffic as incoming if DstAS **AND** DstAddr set to the given values **OR** SrcAddr is in the given range
