### ISSUE TITLE
On-the-fly aggregation/sampling of data

### ISSUE THREAD

**Issue by vidister** [monogon-dev/NetMeta#76]
We're running a NetMeta instance with ~100M flows per day and even basic queries make grafana struggle to display the graphs in 24 hour view. With the default dashboard and no sections opened the tab crashes after a few seconds.
The `Traffic per Ingress Interface` panel fetches >10 Mb of json, the heatmaps load almost a Gigabyte of json.

I see that there already is issue #46 about downsampling for long-term storage. I believe we also need to pre-aggregate or sample data on the fly for the grafana dashboards, depending on the displayed time-range. How do we do this best without smoothing out our peaks too much?

**Comment by leoluk** [comment]
Had a call recently with Altinity to improve the schema, here's some notes: https://github.com/monogon-dev/NetMeta/commit/8cd223f56071b5cbb7dc39f0cb54f6e06521cfc0

Planning to incorporate these soon. ClickHouse also has native support for sampling, however, it's hard to actually sample data proportionally for lack of a true sampling key (like a packet/flow counter).

**Comment by leoluk** [comment]
>  With the default dashboard and no sections opened the tab crashes after a few seconds.

What are the expensive high-cardinality panels? Only the ingress interfaces? Or next hops?

While the queries take longer with more data, the amount of data for the aggregated panels should roughly stay the same.

**Comment by vidister** [comment]
For example the next-hops are quiet bad. ~75 Mb of JSON in the 24 hour view. We have a lot of next-hops, so that's probably inflating it.
```bash
$ curl ... | jq '.data | group_by(.NextHop) | length'
2217
```

**Comment by leoluk** [comment]
Oh no - okay, that explains it :laughing: 

As a quick fix for that, wdyt about moving the next hops panel to a separate expando?

**Comment by vidister** [comment]
Yup. Or we limit it to the top 50 next-hops and break out more detailed views to different dashboards?

**Comment by leoluk** [comment]
That sounds good as well.

Are there any other explode-y dimensions in your data? I'll probably have to simulate your workload to make the right kind of optimizations.

**Comment by leoluk** [comment]
Just so I get an idea for cardinality, could you please run this query on your dataset and share the result (email is in my profile, if you don't want to post it publicly?)

```
kubectl exec -it chi-netmeta-netmeta-0-0-0 -c clickhouse -- clickhouse-client -mn <<EOF
SELECT
    uniqHLL12(FlowType),
    uniqHLL12(FlowDirection),
    uniqHLL12(SamplerAddress),
    uniqHLL12(SrcAddr),
    uniqHLL12(DstAddr),
    uniqHLL12(EType),
    uniqHLL12(Proto),
    uniqHLL12(SrcPort),
    uniqHLL12(DstPort),
    uniqHLL12(InIf),
    uniqHLL12(OutIf),
    uniqHLL12(SrcMac),
    uniqHLL12(DstMac),
    uniqHLL12(SrcVlan),
    uniqHLL12(DstVlan),
    uniqHLL12(VlanId),
    uniqHLL12(IngressVrfId),
    uniqHLL12(EgressVrfId),
    uniqHLL12(IPTos),
    uniqHLL12(ForwardingStatus),
    uniqHLL12(IcmpType),
    uniqHLL12(IcmpCode),
    uniqHLL12(IPv6FlowLabel),
    uniqHLL12(FragmentId),
    uniqHLL12(FragmentOffset),
    uniqHLL12(BiFlowDirection),
    uniqHLL12(SrcAS),
    uniqHLL12(DstAS),
    uniqHLL12(NextHop),
    uniqHLL12(NextHopAS),
    uniqHLL12(SrcNet),
    uniqHLL12(DstNet)
FROM flows_raw FORMAT JSONEachRow
EOF
```

**Comment by vidister** [comment]
Here wo go:
```json
{
  "uniqHLL12(FlowType)": "1",
  "uniqHLL12(FlowDirection)": "1",
  "uniqHLL12(SamplerAddress)": "4",
  "uniqHLL12(SrcAddr)": "6049694",
  "uniqHLL12(DstAddr)": "3223899",
  "uniqHLL12(EType)": "2",
  "uniqHLL12(Proto)": "12",
  "uniqHLL12(SrcPort)": "64212",
  "uniqHLL12(DstPort)": "64212",
  "uniqHLL12(InIf)": "31",
  "uniqHLL12(OutIf)": "33",
  "uniqHLL12(SrcMac)": "1",
  "uniqHLL12(DstMac)": "1",
  "uniqHLL12(SrcVlan)": "22",
  "uniqHLL12(DstVlan)": "1",
  "uniqHLL12(VlanId)": "22",
  "uniqHLL12(IngressVrfId)": "1",
  "uniqHLL12(EgressVrfId)": "1",
  "uniqHLL12(IPTos)": "156",
  "uniqHLL12(ForwardingStatus)": "1",
  "uniqHLL12(IcmpType)": "131",
  "uniqHLL12(IcmpCode)": "117",
  "uniqHLL12(IPv6FlowLabel)": "1",
  "uniqHLL12(FragmentId)": "63035",
  "uniqHLL12(FragmentOffset)": "1",
  "uniqHLL12(BiFlowDirection)": "1",
  "uniqHLL12(SrcAS)": "40449",
  "uniqHLL12(DstAS)": "25668",
  "uniqHLL12(NextHop)": "2634",
  "uniqHLL12(NextHopAS)": "1",
  "uniqHLL12(SrcNet)": "50",
  "uniqHLL12(DstNet)": "48"
}
```

**Comment by vidister** [comment]
btw, after limiting the number of next-hops to 100 the whole dashboard has become quiet usable. Looks like it was primarily the fault of that one panel.
I can submit a PR, if you agree. 100 sounds like a reasonable number for me, what do you think?
In addition I'll build a few more detailed dashboards and filter presets when I find the time.

**Comment by leoluk** [comment]
> I can submit a PR, if you agree. 100 sounds like a reasonable number for me, what do you think?

Sounds good :+1:

**Comment by fionera** [comment]
Implemented via https://github.com/monogon-dev/NetMeta/commit/d1366dfdf5da71d0956ebf0b5b07d1bcbb5a6036
