### ISSUE TITLE
Add Sankey Panel plugin to Grafana

### ISSUE THREAD

**Issue by vidister** [monogon-dev/NetMeta#83]
Sankey Diagrams could be useful for displaying traffic relations.

https://grafana.com/grafana/plugins/netsage-sankey-panel/

**Comment by vidister** [comment]
I've added the Plugin to our instance and clicked some basic traffic-relations graphs. I would like to contribute this to the project. @leoluk what do you think, should I add an additional dashboard for traffic relations?

![traffic_relations](https://user-images.githubusercontent.com/11413574/152782682-161a0add-deae-45fe-8a14-a96659e1b57b.png)

**Comment by leoluk** [comment]
That's super cool - yes please :)

**Comment by vidister** [comment]
So far it's really useful. Unfortunately the Sankey Plugin doesn't support filtering by clicking on a node, that would be really nice..

![traffic_relations](https://user-images.githubusercontent.com/11413574/152804031-358bee5b-fba6-403d-ab5e-11ea9761a2d7.png)

Do you have some ideas what else I could implement? So far I have:
* In/Outbound traffic relations (ASN)
* In/Outbound traffic relations (ASN) via interface
* Top flows (grouped by IP)
* Top flows (grouped by IP+Port)

**Comment by leoluk** [comment]
That's pretty comprehensive - can't think of other fields amenable to being visualized like that.

Perhaps Source AS to destination port?

**Comment by fionera** [comment]
Added with https://github.com/monogon-dev/NetMeta/commit/404ed04567d909a5b8d8c6aa20c30fe550816016
