### ISSUE TITLE
Single-Node Setup: Debian 11 support

### ISSUE THREAD

**Issue by vidister** [monogon-dev/NetMeta#99]
The K3s version `v1.20.0+k3s2` that `install.sh` wants to install fails with a restart loop. `v1.20.15+k3s1` works.

I also tested the current `v1.25`, though that complained upon apply that `k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1` is not available.

**Comment by fionera** [comment]
This is fixed on the https://github.com/monogon-dev/NetMeta/tree/dev/upgrade-versions branch. Its currently in review at https://review.monogon.dev/c/NetMeta/+/958

**Comment by fionera** [comment]
Fixed with https://github.com/monogon-dev/NetMeta/commit/1734a30dac06ba9289bcb115e0db95e5d47edc68
